#!/bin/bash
#!sample PBS submit file -- modify for your system

#PBS -q regular
#PBS -m abe
#PBS -j oe
#PBS -l nodes=8:ppn=8
#PBS -l walltime=4:00:00


cd $PBS_O_WORKDIR

export PBS_JOBNAME="myrun"
echo $PBS_JOBNAME > jobname
echo $PBS_JOBID > jobid
cat $PBS_NODEFILE > hosts.$PBS_JOBID
mpiexec --mca btl ^tcp ./tristan-mp2d > out
