#!/bin/sh
#$ -l h_cpu=96:00:00
#$ -cwd
##$ -P mhd
#$ -pe openmpi-ib 2
##/usr/mpi/pgi/openmpi-1.2.8/bin/mpirun tristan-mp2d
##source /etc/profile.d/modules.sh add mpi/pgi/openmpi/1.4.3
module add mpi/gcc/openmpi/1.4.4
mpirun tristan-mp2d
